### PR TITLE
Allow statement name to be configurable

### PR DESCRIPTION
**Pull request by dorilla**
This is a stab at allowing users to set the statement name from the hardcoded `stmt` default value. One thing I'm unsure about is where to add this. My approach was to add `statement_name` as a property on the `Session`, but a huge drawback is that all queries using the Session would use that name, which may not make the most sense.

Another option is to add an argument to the `Prestige#execute`  function. This approach seems best, but the optional `args` argument would conflict with adding an argument and would require a breaking change. Open to other ideas on this front though.

Also, I'm not sure how best to test this. Should I make sure `Client.execute` is called with a custom name? I don't think Presto returns us anything useful for this.

Let me know what you think!

Just a note about why someone would want this:
It makes it easier to debug in the Presto UI because all you would see is 
image

So having custom names can help if there are a lot of queries running at a time.

### CODE REVIEW

**Comment by bbalser** [comment]
Hello dorilla,
Thank you for the PR!  You should be able to change the name of the statement by using Prestige.prepare/3 and Prestige.execute/3.  Would you prefer to be able to change name without preparing the statement?  We could create a query/4 and default the name if not supplied.  Would that be better for your use case?

**Comment by dorilla** [comment]
@bbalser Hey thanks. Yes I would prefer a `query/4`. Though when I tried, it would conflict with `query/3` because of the optional `args` argument. I'm relatively new to Elixir so I'm not so sure how to fix that issue without a breaking change.

**Comment by bbalser** [comment]
I created a PR to hopefully address your concern, if it works for you, I will merge and push to hex tomorrow.

https://github.com/smartcitiesdata/prestige/pull/21

**Comment by dorilla** [comment]
Fixed by #21

**Pull request closed without merging**
